### ISSUE TITLE
No Instance(s) Available.

### ISSUE THREAD

**Issue by ghost** [x00bence/lol-aram-boost#1]
```
Traceback (most recent call last):
File "C:\Users\USER\Documents\Programming\Python\LOL API\Test.py", line 16, in <module>
port = re.findall(r'"--app-port=(.*?)"', output)[0]
IndexError: list index out of range
```

**Comment by x00bence** [comment]
This problem usually occurs if you are running League of Legends with Administrator rights. In that case, the script will be unable to query information about the League of Legends process. Running the script itself with Administrator rights should help your issue. 

However, as a note: lol-aram-boost has been deprecated because of API changes, rendering it useless.
Read more at: f8db25e
